dent_site/urls.py
from django.urls import path
from . import views

app_name = 'dent_site'

urlpatterns = [
  path('', views.home, name='home'),
  path('concept/', views.concept, name='concept'),
  path('first_visit/', views.first, name='first'),
  path('staff/', views.staff, name='staff'),
  path('general/', views.general, name='general'),
  path('pediatric', views.pediatric, name='pediatric'),
  path('treatment', views.treatment, name='treatment'),
  path('cosmetic', views.cosmetic, name='cosmetic'),
  path('orthodontics', views.orthodontics, name='orthodontics'),
  path('implant', views.implant, name='implant'),
  path('reqruit', views.recruit, name='recruit'),
  path('access', views.access, name='access'),
  path('hkc', views.hkc, name='hkc'),
  path('privacy', views.privacy, name='privacy'),
  path('news/', views.ListNewsView.as_view(), name='news'),
  path('news/<int:pk>/detail', views.DetailNewsView.as_view(), name='news_detail'),
  path('column', views.ListColumnView.as_view(), name='column'),
  path('column/<int:pk>/detail', views.DetailColumnView.as_view(), name='column_detail'),
]

harmony_dent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dent_site.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dent_site/models.py
from django.db import models

class News(models.Model):
  date = models.DateField()
  title = models.CharField(max_length=50)
  text = models.TextField()

  def __str__(self):
    return self.title

class Column(models.Model):
  date = models.DateField()
  title = models.CharField(max_length=50)
  text = models.TextField()

  def __str__(self):
    return self.title

dent_site/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from .consts import ITEM_PER_PAGE
from .models import News, Column

def home(request):
    contents = News.objects.order_by('date').reverse()[0:3]
    context = {
        'contents': contents,
    }
    return render(request, 'dent_site/home.html', context)

def concept(request):
    return render(request, 'dent_site/concept.html')

def first(request):
    return render(request, 'dent_site/first.html')

def staff(request):
    return render(request, 'dent_site/staff.html')

def general(request):
    return render(request, 'dent_site/general.html')

def pediatric(request):
    return render(request, 'dent_site/pediatric.html')

def treatment(request):
    return render(request, 'dent_site/treatment.html')

def cosmetic(request):
    return render(request, 'dent_site/cosmetic.html')

def orthodontics(request):
    return render(request, 'dent_site/orthodontics.html')

def implant(request):
    return render(request, 'dent_site/implant.html')

def recruit(request):
    return render(request, 'dent_site/recruit.html')

def access(request):
    return render(request, 'dent_site/access.html')

def hkc(request):
    return render(request, 'dent_site/hkc.html')

def privacy(request):
    return render(request, 'dent_site/privacy.html')

class ListNewsView(ListView):
    template_name = 'dent_site/news.html'
    model = News
    def get_queryset(self):
        return News.objects.order_by('-date')
    paginate_by = ITEM_PER_PAGE

class DetailNewsView(DetailView):
    template_name = 'dent_site/news_detail.html'
    model = News

class ListColumnView(ListView):
    template_name = 'dent_site/column.html'
    model = Column
    def get_queryset(self):
        return Column.objects.order_by('-date')
    paginate_by = ITEM_PER_PAGE

class DetailColumnView(DetailView):
    template_name = 'dent_site/column_detail.html'
    model = Column

# def news(request):
#     object_list = News.objects.order_by('-date')
#     paginator = Paginator(object_list, ITEM_PER_PAGE)
#     page_number = request.GET.get('page', 1)
#     page_obj = paginator.page(page_number)
#     return render(request, 'dent_site/news.html', {'object_list': object_list, 'page_obj': page_obj})

# def column(request):
#     object_list = Column.objects.order_by('-date')
#     paginator = Paginator(object_list, ITEM_PER_PAGE)
#     page_number = request.GET.get('page', 1)
#     page_obj = paginator.page(page_number)
#     return render(request, 'dent_site/column.html', {'object_list': object_list, 'page_obj': page_obj})

dent_site/templates/dent_site/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %} | 岡山市の歯科医院「医療法人Melody わかさハーモニー歯科」</title>

  <script src="{% static 'dent_site/js/slide.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'dent_site/js/calender.js' %}"></script>
  
  <link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/reset.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/header.css' %}">
  <!-- home.css or sub.css -->
  {% block head %}{% endblock head %} 
  <link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/footer.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/responsive.css' %}">
</head>

  <body>
    <!-- 葉の背景 -->
    <div class="pc-only">
      <div class="position-absolute leaf">
        <img class="w-100 img-fluid" src="../media/img/header/leaf.png">
      </div>
    </div>
  
    <!-- ヘッダー -->
    <header>
      <!-- ロゴ、予約、電話 -->
      <div class="h-container back-green text-md-center">
        <div class="responsive-container d-xl-flex justify-content-center">
          <!-- ロゴ -->
          <div class="my-auto">
            <a href="#">
              <img class="h-logo img-fluid" src="../media/img/header/logo.png" alt="岡山市の歯科医院「医療法人Melody わかさハーモニー歯科」">
            </a>
          </div>
          <!-- 予約、電話 -->
          <div class="pc-only">
            <div class="d-flex justify-content-xl-between justify-content-md-center">
              <!-- ネット予約バナー -->
              <a class="h-banner my-auto" href="https://ssl.haisha-yoyaku.jp/s5747179/login/serviceAppoint/index?SITE_CODE=hp">
                <div>
                  <p>24時間 受付中</p>
                  <p><span>ネット予約はこちら</span></p>
                </div>
              </a>
              <!-- 電話番号、スケジュール -->
              <div class="h-tel">
                <a href="tel:0869033677" class="tel">086-903-3677</a>
                <div class="h-schedule">
                  <p><span class="week">月火水金</span><span class="time">9:00～13:00 / 15:00～19:00</span></p>
                  <p><span class="week">土曜日</span><span class="time">9:00～12:30 / 14:00～17:00</span></p>
                </div>
              </div>
            </div>
          </div>
          <nav class="gMenu sp-only">
            <input class="menu-btn" type="checkbox" id="menu-btn">
            <label class="menu-icon" for="menu-btn">
              <span class="navicon"></span>
            </label>
            <ul class="menu">
              <div>
                <a href="tel:0869033677" class="tel text-center red">086-903-3677</a>
                <a class="h-banner mb-2" href="https://ssl.haisha-yoyaku.jp/s5747179/login/serviceAppoint/index?SITE_CODE=hp">
                  <p>24時間 受付中</p>
                  <p><span>ネット予約はこちら</span></p>
                </a>
                <p class="text-center"><span class="week">月火水金</span><span class="time">9:00～13:00 / 15:00～19:00</span></p>
                <p class="text-center"><span class="week">土曜日</span><span class="time">9:00～12:30 / 14:00～17:00</span></p>
                <li><a href="{% url 'dent_site:home' %}">ホーム</a></li>
                <li><a href="{% url 'dent_site:concept' %}">コンセプト</a></li>
                <li><a href="{% url 'dent_site:staff' %}">スタッフ</a></li>
                <p>診療案内</p>
                <ul class="point d-flex flex-wrap">
                  <li><a href="{% url 'dent_site:general' %}">一般歯科</a></li>
                  <li><a href="{% url 'dent_site:pediatric' %}">小児歯科</a></li>
                  <li><a href="{% url 'dent_site:treatment' %}">予防歯科</a></li>
                  <li><a href="{% url 'dent_site:cosmetic' %}">審美治療・ホワイトニング</a></li>
                  <li><a href="{% url 'dent_site:orthodontics' %}">矯正歯科</a></li>
                  <li><a href="{% url 'dent_site:implant' %}">入れ歯・インプラント治療</a></li>
                </ul>
                <li><a href="{% url 'dent_site:recruit' %}">採用情報</a></li>
                <ul class="point">
                  <a href="{% url 'dent_site:access' %}">医院案内・アクセス</a>
                  <li><a href="{% url 'dent_site:hkc' %}">ハーモニーキッズクラブ</a></li>
                </ul>
              </div>
            </ul>
          </nav>
        </div>
      </div>
    </header>
  
    <!-- nav -->
    <div class="g-navi back-green position-sticky w-100">
      <nav class="pc-only mx-auto">
        <ul class="gnavi__lists d-flex">
          <a href="{% url 'dent_site:home' %}" class="gnavi__list">
            <li>
              <span class="n-img"><img class="img-fluid" src="../media/img/header/home.png"></span>
              <span class="jp">ホーム</span>
            </li>
          </a>
          <a href="{% url 'dent_site:concept' %}" class="gnavi__list">
            <li>
              <span class="n-img"><img class="img-fluid" src="../media/img/header/concept.png"></span>
              <span class="jp">コンセプト</span>
            </li>
          </a>
          <a href="{% url 'dent_site:staff' %}" class="gnavi__list">
            <li>
              <span class="n-img"><img class="img-fluid" src="../media/img/header/staff.png"></span>
              <span class="jp">スタッフ紹介</span>
            </li>
          </a>
          <li class="gnavi__list">
            <a href="#">
              <span class="n-img"><img class="img-fluid" src="../media/img/header/treatment.png"></span>
              <span class="jp">診療案内</span>
            </a>
            <ul class="dropdown__lists">
              <li class="dropdown__list line-center">
                <a href="{% url 'dent_site:general' %}">一般歯科</a>
              </li>
              <li class="dropdown__list line-center">
                <a href="{% url 'dent_site:pediatric' %}">小児歯科</a>
              </li>
              <li class="dropdown__list line-center">
                <a href="{% url 'dent_site:treatment' %}">予防治療</a>
              </li>
              <li class="dropdown__list">
                <a href="{% url 'dent_site:cosmetic' %}">審美治療・<br>ホワイトニング</a>
              </li>
              <li class="dropdown__list line-center">
                <a href="{% url 'dent_site:orthodontics' %}">矯正歯科</a>
              </li>
              <li class="dropdown__list">
                <a href="{% url 'dent_site:implant' %}">入れ歯・<br>インプラント治療</a>
              </li>
            </ul>
          </li>
          <a href="{% url 'dent_site:recruit' %}" class="gnavi__list">
            <li>
              <span class="n-img"><img class="img-fluid" src="../media/img/header/recruit.png"></span>
              <span class="jp">採用情報</span>
            </li>
          </a>
          <li class="gnavi__list" style="padding: 8px 10px 0 10px; width: 21%;">
            <a href="{% url 'dent_site:access' %}">
              <span class="n-img"><img class="img-fluid" src="../media/img/header/access.png"></span>
              <span class="jp">医院案内・アクセス</span>
            </a>
            <ul class="dropdown__lists">
              <li class="dropdown__list">
                <a href="{% url 'dent_site:hkc' %}">ハーモニー<br>キッズクラブ</a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>

    {% block content %}{% endblock content %}

    <!-- フッター -->
    <footer>
      <div class="container">
      <!-- マップ -->
      <div class="row mt-40 mb-40">
        <div class="map col-md-12 col-lg-6 mb-3">
          <iframe src="https://www.google.com/maps/embed?pb=!1m19!1m8!1m3!1d6564.63538712911!2d133.8611443!3d34.646678900000005!3m2!1i1024!2i768!4f13.1!4m8!3e2!4m0!4m5!1s0x3553ff5112725d1b%3A0x5faeb4b27aa2fb07!2z44CSNzAxLTAxNTEg5bKh5bGx55yM5bKh5bGx5biC5YyX5Yy65bmz6YeO77yV77yT77yU4oiS77yR77yVIOOCj-OBi-OBleODj-ODvOODouODi-ODvOatr-enkQ!3m2!1d34.6466789!2d133.8611443!5e0!3m2!1sja!2sjp!4v1574907361218!5m2!1sja!2sjp"></iframe>
        </div>
        <div class="col-md-12 col-lg-6 text-center">
          <!-- ロゴ、住所、アクセス -->
          <div class="mb-3">
            <figure class="mb-3">
              <a href="#">
                <img class="img-fluid" src="../media/img/footer/f-logo.png" alt="">
              </a>
            </figure>
            <p class="address mb-3">
              <span class="badge back-green">所在地</span>
              <br class="sp-only">〒701-0151　岡山県岡山市北区平野534-15
            </p>
            <ul class="list">
              <li>JR山陽本線『庭瀬駅』より徒歩13分</li>
              <li>岡電バス・中鉄バス・両備バス、倉敷方面行き<br>『平野停留所』下車</li>
              <li>駐車場：有</li>
            </ul>
          </div>
          <!-- 電話、バナー -->
          <div class="mb-3">
            <div class="f-tel">
              <div class="tel">
                <a href="tel:0869033677">
                  086-903-3677
                </a>
              </div>
              <div class="f-banner ms-3">
                <a href="#">
                  <p>24時間 受付中</p>
                  <p><span>ネット予約はこちら</span></p>
                </a>
              </div>
            </div>
          </div>
          <!-- スケジュール表 -->
          <table class="f-schedule table table-bordered">
            <thead class="thead-green">
              <tr>
                <th scope="col">診療時間</th>
                <th scope="col">月</th>
                <th scope="col">火</th>
                <th scope="col">水</th>
                <th scope="col">木</th>
                <th scope="col">金</th>
                <th scope="col">土</th>
                <th scope="col">日</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">9:00～13:00</th>
                <td>○</td>
                <td>○</td>
                <td>○</td>
                <td>×</td>
                <td>○</td>
                <td>▲</td>
                <td>×</td>
              </tr>
              <tr>
                <th scope="row">15:00～19:00</th>
                <td>○</td>
                <td>○</td>
                <td>○</td>
                <td>×</td>
                <td>○</td>
                <td>▲</td>
                <td>×</td>
              </tr>
            </tbody>
          </table>
          <p class="caption">
            <span class="color">▲</span> 9:00～12:30 / 14:00～17:00 <br>［休診日］木曜・日曜・祝日
          </p>
        </div>
      </div>
      </div>
      <div class="back-yellow sns">
        <div class="mx-auto d-flex justify-content-evenly">
          <a href="https://www.instagram.com/hamonichike/" target="_blank" rel="noopener noreferrer" title="@hamonichike" class="sbi_header_link">
            <img class="img-fluid" src="../media/img/footer/Instagram.png" alt="">
          </a>
          <a href="https://www.facebook.com/people/%E3%82%8F%E3%81%8B%E3%81%95-%E3%83%8F%E3%83%BC%E3%83%A2%E3%83%8B%E3%83%BC%E6%AD%AF%E7%A7%91/100026159666349/" target="_blank" rel="noopener noreferrer" title="@hamonichike" class="sbi_header_link">
            <img class="img-fluid" src="../media/img/footer/fb.png" alt="">
          </a>
          <a href="">
            <img class="img-fluid" src="../media/img/footer/X.png" alt="">
          </a>
          <a href="">
            <img class="img-fluid" src="../media/img/footer/LINE.png" alt="">
          </a>
          <a href="{% url 'dent_site:privacy' %}" class="privacy">プライバシー<br class="sp-only">ポリシー</a>
        </div>
      </div>
      <small><p class="copyright">© 2019 医療法人Melody わかさハーモニー歯科.</p></small>
    </footer>
    <div id="sp-fixed-menu" class="for-sp sp-only">
      <ul>
        <li><a href="https://ssl.haisha-yoyaku.jp/s5747179/login/serviceAppoint/index?SITE_CODE=hp">ネット予約</a></li>
        <li><a href="tel:0869033677">お問い合わせ</a></li>
      </ul>
    </div>    
  </body>
</html>

dent_site/templates/dent_site/components/pagination.html
{% if page_obj.has_other_pages %}
  <ul class="list-unstyled mt-5 d-flex justify-content-between">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;前へ</a></li>
    {% else %}
      <li class="text-muted">&lt;&lt;前へ</li>
    {% endif %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">次へ&gt;&gt;</a></li>
    {% else %}
      <li class="text-muted">次へ&gt;</li>
    {% endif %}
  </ul>
{% endif %}

dent_site/templates/dent_site/home.html
{% extends './base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/home.css' %}">
{% endblock head %}

{% block content %}
<!-- スライドショー -->
<div class="slide position-relative">
  <h1 class="position-absolute text-center">「ここにきてよかった」「また来たい」<br>そう思える医院づくりを心がけております。</h1>
  <img class="h-100 w-100" src="media/photo/home/slide1.jpg"/>
  <img class="h-100 w-100 position-absolute" src="media/photo/home/slide2.jpg" style="left: 0;"/>
  <img class="h-100 w-100 position-absolute" src="media/photo/home/slide3.jpg"  style="left: 0;"/>
</div>

<!-- メイン -->
<main>
  <!-- ニュース -->
  <div class="news-container back-green py-80 position-relative" style="height: 500px;">
    <div class="news-back mx-auto" style="background-image: url(/media/img/home/news.jpg);">
      <div class="news">
        <h2 class="en green py-3">NEWS</h2>
        {% for content in contents %}
          <div>
            <div class="row py-2 g-0">
              <time class="col-2 offset-1">{{ content.date }}</time>
              <a href="{% url 'dent_site:news_detail' content.pk %}" class="txt fw-bold col-8">{{ content.title }}</a>
            </div>
          </div>
        {% endfor %}
        <div class="text-center">
          <a href="{% url 'dent_site:news' %}" class="btn btn-outline-success mt-4">記事一覧</a>
        </div>
      </div>
    </div>
    <div class="wave"></div>
  </div>

  <div class="py-80">
    <div class="d-flex justify-content-center">
      <img class="hedgehog col-6" src="media/img/home/first.png">
      <div class="bubble position-relative">
        <p class="txt">初めて診察を受ける方はこちらをご覧ください</p>
        <a href="{% url 'dent_site:first' %}" class="en"><div class="click-btn">click</div></a>
      </div>
    </div>
  </div>

  <div class="back-yellow py-80 text-center">
    <div class="container">
      <h2 class="mb-3">
        <span class="jp">岡山市で地域の皆さまの<br class="sp-only">
          <span class="green">健康を守る歯科医院</span></span>
        <span class="en">Concept</span>
      </h2>
      <p class="mx-auto" style="width: 70%;">
        病気を起こすことのない健康なお口を維持していくことにより、<span class="marker">生涯に渡り幸せな生活</span>を送っていただくことで、地域の皆様に<span class="marker">笑顔とQ.O.L（生活の質）の向上</span>を提供いたします。<br>
        予防・メンテナンスに力を入れており、患者様と同じ目線で、なるべく歯を削らない・抜かない・痛みの少ない治療を目指しております。
      </p>
      <a class="d-btn btn btn-success mt-5" href="{% url 'dent_site:concept' %}" role="button">詳しくはこちら</a>
    </div>
  </div>

  <div class="treatment_back py-80" style="background-image: url(/media/img/home/back.jpg);">
    <div class="treatment container">
      <h2 class="mb-5">こんな<span class="green">お悩み</span>はありませんか？</h2>
      <div class="row text-center">
        <div class="col-6 col-lg-4">
          <div class="item mb-3">
            <a href="{% url 'dent_site:general' %}" class="item-thumb">
              <figure><img class="img-fluid" src="media/img/home/general.png"></figure>
              <div class="jp">歯が痛い・歯茎が痛い</div>
            </a>
            <h3>一般歯科</h3>
          </div>
        </div>
        <div class="col-6 col-lg-4">
          <div class="item mb-3">
            <a href="{% url 'dent_site:pediatric' %}" class="item-thumb">
              <figure><img class="img-fluid" src="media/img/home/pediatric.png"></figure>
              <div class="jp">子供の歯並びが気になる</div>
            </a>
            <h3>小児歯科</h3>
          </div>
        </div>
        <div class="col-6 col-lg-4">
          <div class="item mb-3">
            <a href="{% url 'dent_site:treatment' %}" class="item-thumb">
              <figure><img class="img-fluid" src="media/img/home/treatment.png"></figure>
              <div class="jp">綺麗な歯を維持したい</div>
            </a>
            <h3>予防治療</h3>
          </div>
        </div>
        <div class="col-6 col-lg-4">
          <div class="item mb-3">
            <a href="{% url 'dent_site:cosmetic' %}" class="item-thumb">
              <figure><img class="img-fluid" src="media/img/home/cosmetic.png" style="padding: 10px;"></figure>
              <div class="jp">歯を白くしたい</div>
            </a>
            <h3>審美治療・<br>ホワイトニング</h3>
          </div>
        </div>
        <div class="col-6 col-lg-4">
          <div class="item mb-3">
            <a href="{% url 'dent_site:orthodontics' %}" class="item-thumb">
              <figure><img class="img-fluid" src="media/img/home/orthodontics.png" style="padding: 20px 0;"></figure>
              <div class="jp">矯正器具が目立つのが嫌だ</div>
            </a>
            <h3>矯正歯科</h3>
          </div>
        </div>
        <div class="col-6 col-lg-4">
          <div class="item mb-3">
            <a href="{% url 'dent_site:implant' %}" class="item-thumb">
              <figure><img class="img-fluid" src="media/img/home/implant.png" style="padding: 0 25px;"></figure>
              <div class="jp">しっかり噛めるようになりたい</div>
            </a>
            <h3>入れ歯・<br>インプラント治療</h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="py-80">
    <div class="container circle">
      <h2 class="mb-5">当院の<span class="red">設備紹介</span></h2>
      <div class="row">
        <div class="col-md-12 col-lg-6">
          <div class="row">
            <figure class="col-6"><img class="img-fluid mb-3" src="media/photo/home/facility01.jpg"></figure>
            <figure class="col-6"><img class="img-fluid mb-3" src="media/photo/home/facility02.jpg"></figure>
          </div>
        </div>
        <div class="col-lg-6">
          <h3 class="f-ttl green">どなたも安心して通える<br>快適な医院づくりを目指して</h3>
          <p>当院にご来院いただく全ての患者様に、安心して治療を受けていただけるように、診療で使う機器の滅菌対策を徹底して、感染症予防に努めております。<br>
          また、お子様からご高齢の方まで、ご来院いただく全ての患者様が、快適に通院できるような医院づくりを心がけております。
          </p>
          <a class="d-btn btn btn-success mt-5 mx-auto" href="{% url 'dent_site:access' %}" role="button">詳しくはこちら</a>
        </div>
      </div>
    </div>
  </div>

  <div class="back-yellow py-80">
    <div class="container">
      <h2 class="mb-5 red">院長・スタッフ紹介</h2>
      <div class="row flex-row-reverse">
        <figure class="col-md-12 col-lg-6 mb-3"><img class="img-fluid" src="media/photo/staff.jpg" alt="スタッフ写真"></figure>
        <div class="col-md-12 col-lg-6">
          <p>当院は、日々技術を磨いて研鑽を重ね、学会などにも積極的に参加し、患者様に喜んでもらおうとみんなで協力している歯科医院です。<br>
          スタッフは皆前向きで明るく、やる気に満ち溢れています。</p>
          <a class="d-btn btn btn-success mt-5 mx-auto" href="{% url 'dent_site:staff' %}" role="button">詳しくはこちら</a>
        </div>
      </div>
    </div>
  </div>

  <div class="back-green py-80">
    <div class="container">
      <h2 class="mb-5"><span class="red">予約制</span>についてのご案内</h2>
      <p class="mx-auto text-center" style="width: 65%;">
        当院は、予約制となっております。<br>
        歯科医療では、お約束のお時間に合わせて、その患者様一人ひとりに合わせた専用の器具を滅菌・消毒の上、準備してお待ちする必要がございます。<br>
        そのため、極力「急なご予約の変更」「ご連絡なしのキャンセル」はご遠慮いただければ幸いです。
      </p>
      <div class="reserve_box">
        <div class="business-calendar-box d-md-flex justify-content-lg-between">
          <div class="cal01">
            <!--今月のカレンダー-->
            <script type="text/javascript">
              setCalender();
            </script>
            </div>
          <div class="cal02">
            <!--翌月のカレンダー-->
            <script type="text/javascript">
              setCalender2();
            </script>
          </div>
        </div>
        <p class="caption">
          <span class="attr01">休診</span>
          <span class="attr02">午前休診</span>
          <span class="attr03">午後休診</span>
        </p>
      </div>
    </div>
  </div>
      
  <!-- コラム&ブログ -->
  <div class="pagelink container py-80 d-md-flex justify-content-evenly">
    <a href="{% url 'dent_site:column' %}">
      <div class="column position-relative" style="background: url(/media/photo/home/background1.jpg); background-size: cover;"><p class="position-absolute text-center w-100">コラム</p></div>
    </a>
    <a href="https://ameblo.jp/harmonydent/" target="_blank" rel="noopener noreferrer">
      <div class="blog position-relative" style="background: url(/media/photo/home/background2.jpg); background-size: cover;"><p class="position-absolute text-center w-100">院長・スタッフのブログ</p></div>
    </a>
  </div>
</main>
{% endblock %}

dent_site/templates/dent_site/subpage.html
{% extends './base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'dent_site/css/sub.css' %}">
{% endblock head %}

{% block content %}

{% endblock %}